#!/usr/bin/env python3
"""Generate main/generated/home_noise.h: a 64x64 blue-noise threshold mask.

Void-and-cluster (Ulichney 1993) from lab/dither/bwry.py, deterministic seed.
Ranks 0..4095 are stored as thresholds 0..255 (rank >> 4), so a coverage p in
0..1 compares as p * 256 > mask. The same mask serves every cell size: index
(x / cell, y / cell), which tiles at 64 * cell pixels (128 px for colour).
Usage: python3 lab/next/tools/build_noise.py [firmware_dir]
"""
import hashlib
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parents[1] / 'dither'))
import bwry  # noqa: E402

N, SIGMA, SEED = 64, 1.5, 0x1234ABCD


def main():
    firmware = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE.parent / 'firmware'
    out = firmware / 'main' / 'generated' / 'home_noise.h'
    rank = bwry.blue_noise(N, SIGMA, SEED)
    flat = [r for row in rank for r in row]
    assert sorted(flat) == list(range(N * N)), 'rank matrix is not a permutation'
    values = [r >> 4 for r in flat]
    digest = hashlib.sha256(bytes(values)).hexdigest()
    lines = [
        '/* Generated by lab/next/tools/build_noise.py: 64x64 blue-noise threshold mask,',
        f' * void-and-cluster, sigma {SIGMA}, seed 0x{SEED:08X}, ranks stored as rank >> 4.',
        f' * sha256 of the 4096 bytes: {digest}. Do not edit by hand. */',
        '#ifndef HOME_NOISE_H',
        '#define HOME_NOISE_H',
        '#include <stdint.h>',
        f'#define HOME_NOISE_SIZE {N}',
        f'static const uint8_t home_noise[{N * N}] = {{',
    ]
    for y in range(N):
        lines.append('    ' + ','.join(f'{v:3d}' for v in values[y * N:(y + 1) * N]) + ',')
    lines += ['};', '#endif', '']
    out.write_text('\n'.join(lines))
    print(f'{out} sha256 {digest}')
    # spectral sanity: every 8x8 window at 50 % has 24..40 dark cells (no clumps, no voids)
    counts = []
    for wy in range(0, N, 8):
        for wx in range(0, N, 8):
            counts.append(sum(1 for y in range(wy, wy + 8) for x in range(wx, wx + 8) if values[y * N + x] < 128))
    print(f'8x8 windows at 50 %: min {min(counts)} max {max(counts)} (ideal 32)')


if __name__ == '__main__':
    main()
